hash-format = "sha256"

[[files]]
file = "config/betterdays-common.toml"
hash = "1c2bdd48c9fcaaac9ed647f9c90d289e1fab5f39ec38e24c0f3eeeff36425863"

[[files]]
file = "config/carpet/scripts/quick_insert.sc"
hash = "1c2bdd48c9fcaaac9ed647f9c90d289e1fab5f39ec38e24c0f3eeeff36425863"

[[files]]
file = "config/computercraft-server.toml"
hash = "1c2bdd48c9fcaaac9ed647f9c90d289e1fab5f39ec38e24c0f3eeeff36425863"

[[files]]
file = "config/construction_wand.conf"
hash = "1c2bdd48c9fcaaac9ed647f9c90d289e1fab5f39ec38e24c0f3eeeff36425863"

[[files]]
file = "config/copperhopper.properties"
hash = "1c2bdd48c9fcaaac9ed647f9c90d289e1fab5f39ec38e24c0f3eeeff36425863"

[[files]]
file = "config/cropsloverain.toml"
hash = "1c2bdd48c9fcaaac9ed647f9c90d289e1fab5f39ec38e24c0f3eeeff36425863"

[[files]]
file = "config/easyanvils-server.toml"
hash = "1c2bdd48c9fcaaac9ed647f9c90d289e1fab5f39ec38e24c0f3eeeff36425863"

[[files]]
file = "config/easymagic-server.toml"
hash = "1c2bdd48c9fcaaac9ed647f9c90d289e1fab5f39ec38e24c0f3eeeff36425863"

[[files]]
file = "config/eclipsestweakeroo-server.json"
hash = "1c2bdd48c9fcaaac9ed647f9c90d289e1fab5f39ec38e24c0f3eeeff36425863"

[[files]]
file = "config/entangled-common.toml"
hash = "1c2bdd48c9fcaaac9ed647f9c90d289e1fab5f39ec38e24c0f3eeeff36425863"

[[files]]
file = "config/extended_drawers.json"
hash = "1c2bdd48c9fcaaac9ed647f9c90d289e1fab5f39ec38e24c0f3eeeff36425863"

[[files]]
file = "config/farmersdelight-common.json"
hash = "1c2bdd48c9fcaaac9ed647f9c90d289e1fab5f39ec38e24c0f3eeeff36425863"

[[files]]
file = "config/faster_hopper.json"
hash = "1c2bdd48c9fcaaac9ed647f9c90d289e1fab5f39ec38e24c0f3eeeff36425863"

[[files]]
file = "config/global_packs.toml"
hash = "1c2bdd48c9fcaaac9ed647f9c90d289e1fab5f39ec38e24c0f3eeeff36425863"

[[files]]
file = "config/gravestones.json"
hash = "1c2bdd48c9fcaaac9ed647f9c90d289e1fab5f39ec38e24c0f3eeeff36425863"

[[files]]
file = "config/highspeed-rail.json5"
hash = "1c2bdd48c9fcaaac9ed647f9c90d289e1fab5f39ec38e24c0f3eeeff36425863"

[[files]]
file = "config/leavesbegone-server.toml"
hash = "1c2bdd48c9fcaaac9ed647f9c90d289e1fab5f39ec38e24c0f3eeeff36425863"

[[files]]
file = "config/letmesleep-server.toml"
hash = "1c2bdd48c9fcaaac9ed647f9c90d289e1fab5f39ec38e24c0f3eeeff36425863"

[[files]]
file = "config/linkedchests-server.toml"
hash = "1c2bdd48c9fcaaac9ed647f9c90d289e1fab5f39ec38e24c0f3eeeff36425863"

[[files]]
file = "config/magnumtorch-server.toml"
hash = "1c2bdd48c9fcaaac9ed647f9c90d289e1fab5f39ec38e24c0f3eeeff36425863"

[[files]]
file = "config/rusticdelight.json"
hash = "1c2bdd48c9fcaaac9ed647f9c90d289e1fab5f39ec38e24c0f3eeeff36425863"

[[files]]
file = "config/sci4me/Torcherino.cfg"
hash = "1c2bdd48c9fcaaac9ed647f9c90d289e1fab5f39ec38e24c0f3eeeff36425863"

[[files]]
file = "config/taxfreelevels.json"
hash = "1c2bdd48c9fcaaac9ed647f9c90d289e1fab5f39ec38e24c0f3eeeff36425863"

[[files]]
file = "config/toms_storage.json"
hash = "1c2bdd48c9fcaaac9ed647f9c90d289e1fab5f39ec38e24c0f3eeeff36425863"

[[files]]
file = "config/universalbonemeal-server.toml"
hash = "1c2bdd48c9fcaaac9ed647f9c90d289e1fab5f39ec38e24c0f3eeeff36425863"

[[files]]
file = "config/universalenchants-server.toml"
hash = "1c2bdd48c9fcaaac9ed647f9c90d289e1fab5f39ec38e24c0f3eeeff36425863"

[[files]]
file = "config/waystones-common.toml"
hash = "1c2bdd48c9fcaaac9ed647f9c90d289e1fab5f39ec38e24c0f3eeeff36425863"

[[files]]
file = "global_packs/required_data/carpet_defaults/data/carpet_defaults/function/load.mcfunction"
hash = "1c2bdd48c9fcaaac9ed647f9c90d289e1fab5f39ec38e24c0f3eeeff36425863"

[[files]]
file = "global_packs/required_data/carpet_defaults/data/minecraft/tags/function/load.json"
hash = "1c2bdd48c9fcaaac9ed647f9c90d289e1fab5f39ec38e24c0f3eeeff36425863"

[[files]]
file = "global_packs/required_data/carpet_defaults/pack.mcmeta"
hash = "1c2bdd48c9fcaaac9ed647f9c90d289e1fab5f39ec38e24c0f3eeeff36425863"

[[files]]
file = "icon.svg"
hash = "1c2bdd48c9fcaaac9ed647f9c90d289e1fab5f39ec38e24c0f3eeeff36425863"

[[files]]
file = "mods/addadd.pw.toml"
hash = "1c2bdd48c9fcaaac9ed647f9c90d289e1fab5f39ec38e24c0f3eeeff36425863"
metafile = true

[[files]]
file = "mods/advanced-netherite.pw.toml"
hash = "1c2bdd48c9fcaaac9ed647f9c90d289e1fab5f39ec38e24c0f3eeeff36425863"
metafile = true

[[files]]
file = "mods/advancements-fullscreen.pw.toml"
hash = "1c2bdd48c9fcaaac9ed647f9c90d289e1fab5f39ec38e24c0f3eeeff36425863"
metafile = true

[[files]]
file = "mods/anvil-unlimited-1.0.0.jar"
hash = "1c2bdd48c9fcaaac9ed647f9c90d289e1fab5f39ec38e24c0f3eeeff36425863"

[[files]]
file = "mods/appleskin.pw.toml"
hash = "1c2bdd48c9fcaaac9ed647f9c90d289e1fab5f39ec38e24c0f3eeeff36425863"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "1c2bdd48c9fcaaac9ed647f9c90d289e1fab5f39ec38e24c0f3eeeff36425863"
metafile = true

[[files]]
file = "mods/attributefix.pw.toml"
hash = "1c2bdd48c9fcaaac9ed647f9c90d289e1fab5f39ec38e24c0f3eeeff36425863"
metafile = true

[[files]]
file = "mods/balm.pw.toml"
hash = "1c2bdd48c9fcaaac9ed647f9c90d289e1fab5f39ec38e24c0f3eeeff36425863"
metafile = true

[[files]]
file = "mods/betterdays-fake-player-fix-1.0.0.jar"
hash = "1c2bdd48c9fcaaac9ed647f9c90d289e1fab5f39ec38e24c0f3eeeff36425863"

[[files]]
file = "mods/betterdays.pw.toml"
hash = "1c2bdd48c9fcaaac9ed647f9c90d289e1fab5f39ec38e24c0f3eeeff36425863"
metafile = true

[[files]]
file = "mods/blaha-replushed.pw.toml"
hash = "1c2bdd48c9fcaaac9ed647f9c90d289e1fab5f39ec38e24c0f3eeeff36425863"
metafile = true

[[files]]
file = "mods/bottle-your-xp.pw.toml"
hash = "1c2bdd48c9fcaaac9ed647f9c90d289e1fab5f39ec38e24c0f3eeeff36425863"
metafile = true

[[files]]
file = "mods/c2me-fabric.pw.toml"
hash = "1c2bdd48c9fcaaac9ed647f9c90d289e1fab5f39ec38e24c0f3eeeff36425863"
metafile = true

[[files]]
file = "mods/carpet-ams-addition.pw.toml"
hash = "1c2bdd48c9fcaaac9ed647f9c90d289e1fab5f39ec38e24c0f3eeeff36425863"
metafile = true

[[files]]
file = "mods/carpet-bot-relog.pw.toml"
hash = "1c2bdd48c9fcaaac9ed647f9c90d289e1fab5f39ec38e24c0f3eeeff36425863"
metafile = true

[[files]]
file = "mods/carpet-extra-extras.pw.toml"
hash = "1c2bdd48c9fcaaac9ed647f9c90d289e1fab5f39ec38e24c0f3eeeff36425863"
metafile = true

[[files]]
file = "mods/carpet-extra.pw.toml"
hash = "1c2bdd48c9fcaaac9ed647f9c90d289e1fab5f39ec38e24c0f3eeeff36425863"
metafile = true

[[files]]
file = "mods/carpet-org-addition.pw.toml"
hash = "1c2bdd48c9fcaaac9ed647f9c90d289e1fab5f39ec38e24c0f3eeeff36425863"
metafile = true

[[files]]
file = "mods/carpet-tis-addition.pw.toml"
hash = "1c2bdd48c9fcaaac9ed647f9c90d289e1fab5f39ec38e24c0f3eeeff36425863"
metafile = true

[[files]]
file = "mods/carpet.pw.toml"
hash = "1c2bdd48c9fcaaac9ed647f9c90d289e1fab5f39ec38e24c0f3eeeff36425863"
metafile = true

[[files]]
file = "mods/cc-tweaked.pw.toml"
hash = "1c2bdd48c9fcaaac9ed647f9c90d289e1fab5f39ec38e24c0f3eeeff36425863"
metafile = true

[[files]]
file = "mods/chatanimation.pw.toml"
hash = "1c2bdd48c9fcaaac9ed647f9c90d289e1fab5f39ec38e24c0f3eeeff36425863"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "1c2bdd48c9fcaaac9ed647f9c90d289e1fab5f39ec38e24c0f3eeeff36425863"
metafile = true

[[files]]
file = "mods/clumps.pw.toml"
hash = "1c2bdd48c9fcaaac9ed647f9c90d289e1fab5f39ec38e24c0f3eeeff36425863"
metafile = true

[[files]]
file = "mods/collective.pw.toml"
hash = "1c2bdd48c9fcaaac9ed647f9c90d289e1fab5f39ec38e24c0f3eeeff36425863"
metafile = true

[[files]]
file = "mods/construction-wand-fabric.pw.toml"
hash = "1c2bdd48c9fcaaac9ed647f9c90d289e1fab5f39ec38e24c0f3eeeff36425863"
metafile = true

[[files]]
file = "mods/copper-hopper.pw.toml"
hash = "1c2bdd48c9fcaaac9ed647f9c90d289e1fab5f39ec38e24c0f3eeeff36425863"
metafile = true

[[files]]
file = "mods/crops-love-rain.pw.toml"
hash = "1c2bdd48c9fcaaac9ed647f9c90d289e1fab5f39ec38e24c0f3eeeff36425863"
metafile = true

[[files]]
file = "mods/crystalcarpetaddition.pw.toml"
hash = "1c2bdd48c9fcaaac9ed647f9c90d289e1fab5f39ec38e24c0f3eeeff36425863"
metafile = true

[[files]]
file = "mods/dark-loading-screen.pw.toml"
hash = "1c2bdd48c9fcaaac9ed647f9c90d289e1fab5f39ec38e24c0f3eeeff36425863"
metafile = true

[[files]]
file = "mods/delight-lib.pw.toml"
hash = "1c2bdd48c9fcaaac9ed647f9c90d289e1fab5f39ec38e24c0f3eeeff36425863"
metafile = true

[[files]]
file = "mods/easy-anvils.pw.toml"
hash = "1c2bdd48c9fcaaac9ed647f9c90d289e1fab5f39ec38e24c0f3eeeff36425863"
metafile = true

[[files]]
file = "mods/easy-magic.pw.toml"
hash = "1c2bdd48c9fcaaac9ed647f9c90d289e1fab5f39ec38e24c0f3eeeff36425863"
metafile = true

[[files]]
file = "mods/eclipses-tweakeroo-additions.pw.toml"
hash = "1c2bdd48c9fcaaac9ed647f9c90d289e1fab5f39ec38e24c0f3eeeff36425863"
metafile = true

[[files]]
file = "mods/entangled.pw.toml"
hash = "1c2bdd48c9fcaaac9ed647f9c90d289e1fab5f39ec38e24c0f3eeeff36425863"
metafile = true

[[files]]
file = "mods/extended-drawers.pw.toml"
hash = "1c2bdd48c9fcaaac9ed647f9c90d289e1fab5f39ec38e24c0f3eeeff36425863"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "1c2bdd48c9fcaaac9ed647f9c90d289e1fab5f39ec38e24c0f3eeeff36425863"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "1c2bdd48c9fcaaac9ed647f9c90d289e1fab5f39ec38e24c0f3eeeff36425863"
metafile = true

[[files]]
file = "mods/fallingleaves.pw.toml"
hash = "1c2bdd48c9fcaaac9ed647f9c90d289e1fab5f39ec38e24c0f3eeeff36425863"
metafile = true

[[files]]
file = "mods/farmers-delight-refabricated.pw.toml"
hash = "1c2bdd48c9fcaaac9ed647f9c90d289e1fab5f39ec38e24c0f3eeeff36425863"
metafile = true

[[files]]
file = "mods/fast-turtles-1.0.0.jar"
hash = "1c2bdd48c9fcaaac9ed647f9c90d289e1fab5f39ec38e24c0f3eeeff36425863"

[[files]]
file = "mods/fastback.pw.toml"
hash = "1c2bdd48c9fcaaac9ed647f9c90d289e1fab5f39ec38e24c0f3eeeff36425863"
metafile = true

[[files]]
file = "mods/faster-hopper.pw.toml"
hash = "1c2bdd48c9fcaaac9ed647f9c90d289e1fab5f39ec38e24c0f3eeeff36425863"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "1c2bdd48c9fcaaac9ed647f9c90d289e1fab5f39ec38e24c0f3eeeff36425863"
metafile = true

[[files]]
file = "mods/forge-config-api-port.pw.toml"
hash = "1c2bdd48c9fcaaac9ed647f9c90d289e1fab5f39ec38e24c0f3eeeff36425863"
metafile = true

[[files]]
file = "mods/fusion-connected-textures.pw.toml"
hash = "1c2bdd48c9fcaaac9ed647f9c90d289e1fab5f39ec38e24c0f3eeeff36425863"
metafile = true

[[files]]
file = "mods/gca.pw.toml"
hash = "1c2bdd48c9fcaaac9ed647f9c90d289e1fab5f39ec38e24c0f3eeeff36425863"
metafile = true

[[files]]
file = "mods/globalpacks.pw.toml"
hash = "1c2bdd48c9fcaaac9ed647f9c90d289e1fab5f39ec38e24c0f3eeeff36425863"
metafile = true

[[files]]
file = "mods/grind-enchantments.pw.toml"
hash = "1c2bdd48c9fcaaac9ed647f9c90d289e1fab5f39ec38e24c0f3eeeff36425863"
metafile = true

[[files]]
file = "mods/highspeed-rail.pw.toml"
hash = "1c2bdd48c9fcaaac9ed647f9c90d289e1fab5f39ec38e24c0f3eeeff36425863"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "1c2bdd48c9fcaaac9ed647f9c90d289e1fab5f39ec38e24c0f3eeeff36425863"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "1c2bdd48c9fcaaac9ed647f9c90d289e1fab5f39ec38e24c0f3eeeff36425863"
metafile = true

[[files]]
file = "mods/item-scroller.pw.toml"
hash = "1c2bdd48c9fcaaac9ed647f9c90d289e1fab5f39ec38e24c0f3eeeff36425863"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
hash = "1c2bdd48c9fcaaac9ed647f9c90d289e1fab5f39ec38e24c0f3eeeff36425863"
metafile = true

[[files]]
file = "mods/jline4mcdsrv.pw.toml"
hash = "1c2bdd48c9fcaaac9ed647f9c90d289e1fab5f39ec38e24c0f3eeeff36425863"
metafile = true

[[files]]
file = "mods/kleeslabs.pw.toml"
hash = "1c2bdd48c9fcaaac9ed647f9c90d289e1fab5f39ec38e24c0f3eeeff36425863"
metafile = true

[[files]]
file = "mods/leaves-be-gone.pw.toml"
hash = "1c2bdd48c9fcaaac9ed647f9c90d289e1fab5f39ec38e24c0f3eeeff36425863"
metafile = true

[[files]]
file = "mods/let-me-sleep-fuzs.pw.toml"
hash = "1c2bdd48c9fcaaac9ed647f9c90d289e1fab5f39ec38e24c0f3eeeff36425863"
metafile = true

[[files]]
file = "mods/litematica-rawmaterials.pw.toml"
hash = "1c2bdd48c9fcaaac9ed647f9c90d289e1fab5f39ec38e24c0f3eeeff36425863"
metafile = true

[[files]]
file = "mods/litematica.pw.toml"
hash = "1c2bdd48c9fcaaac9ed647f9c90d289e1fab5f39ec38e24c0f3eeeff36425863"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "1c2bdd48c9fcaaac9ed647f9c90d289e1fab5f39ec38e24c0f3eeeff36425863"
metafile = true

[[files]]
file = "mods/ly-veinminer-enchantment.pw.toml"
hash = "1c2bdd48c9fcaaac9ed647f9c90d289e1fab5f39ec38e24c0f3eeeff36425863"
metafile = true

[[files]]
file = "mods/magnetic-enchantment.pw.toml"
hash = "1c2bdd48c9fcaaac9ed647f9c90d289e1fab5f39ec38e24c0f3eeeff36425863"
metafile = true

[[files]]
file = "mods/magnum-torch.pw.toml"
hash = "1c2bdd48c9fcaaac9ed647f9c90d289e1fab5f39ec38e24c0f3eeeff36425863"
metafile = true

[[files]]
file = "mods/malilib.pw.toml"
hash = "1c2bdd48c9fcaaac9ed647f9c90d289e1fab5f39ec38e24c0f3eeeff36425863"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "1c2bdd48c9fcaaac9ed647f9c90d289e1fab5f39ec38e24c0f3eeeff36425863"
metafile = true

[[files]]
file = "mods/more-delight.pw.toml"
hash = "1c2bdd48c9fcaaac9ed647f9c90d289e1fab5f39ec38e24c0f3eeeff36425863"
metafile = true

[[files]]
file = "mods/nanite-library.pw.toml"
hash = "1c2bdd48c9fcaaac9ed647f9c90d289e1fab5f39ec38e24c0f3eeeff36425863"
metafile = true

[[files]]
file = "mods/netherportalfix.pw.toml"
hash = "1c2bdd48c9fcaaac9ed647f9c90d289e1fab5f39ec38e24c0f3eeeff36425863"
metafile = true

[[files]]
file = "mods/new-linked-chests.pw.toml"
hash = "1c2bdd48c9fcaaac9ed647f9c90d289e1fab5f39ec38e24c0f3eeeff36425863"
metafile = true

[[files]]
file = "mods/no-chat-reports.pw.toml"
hash = "1c2bdd48c9fcaaac9ed647f9c90d289e1fab5f39ec38e24c0f3eeeff36425863"
metafile = true

[[files]]
file = "mods/placeholder-api.pw.toml"
hash = "1c2bdd48c9fcaaac9ed647f9c90d289e1fab5f39ec38e24c0f3eeeff36425863"
metafile = true

[[files]]
file = "mods/pneumono_core.pw.toml"
hash = "1c2bdd48c9fcaaac9ed647f9c90d289e1fab5f39ec38e24c0f3eeeff36425863"
metafile = true

[[files]]
file = "mods/pneumono_gravestones.pw.toml"
hash = "1c2bdd48c9fcaaac9ed647f9c90d289e1fab5f39ec38e24c0f3eeeff36425863"
metafile = true

[[files]]
file = "mods/prickle.pw.toml"
hash = "1c2bdd48c9fcaaac9ed647f9c90d289e1fab5f39ec38e24c0f3eeeff36425863"
metafile = true

[[files]]
file = "mods/puzzles-lib.pw.toml"
hash = "1c2bdd48c9fcaaac9ed647f9c90d289e1fab5f39ec38e24c0f3eeeff36425863"
metafile = true

[[files]]
file = "mods/quick-shulker.pw.toml"
hash = "1c2bdd48c9fcaaac9ed647f9c90d289e1fab5f39ec38e24c0f3eeeff36425863"
metafile = true

[[files]]
file = "mods/rechiseled.pw.toml"
hash = "1c2bdd48c9fcaaac9ed647f9c90d289e1fab5f39ec38e24c0f3eeeff36425863"
metafile = true

[[files]]
file = "mods/rei.pw.toml"
hash = "1c2bdd48c9fcaaac9ed647f9c90d289e1fab5f39ec38e24c0f3eeeff36425863"
metafile = true

[[files]]
file = "mods/rustic-delight.pw.toml"
hash = "1c2bdd48c9fcaaac9ed647f9c90d289e1fab5f39ec38e24c0f3eeeff36425863"
metafile = true

[[files]]
file = "mods/scalablelux.pw.toml"
hash = "1c2bdd48c9fcaaac9ed647f9c90d289e1fab5f39ec38e24c0f3eeeff36425863"
metafile = true

[[files]]
file = "mods/shogi.pw.toml"
hash = "1c2bdd48c9fcaaac9ed647f9c90d289e1fab5f39ec38e24c0f3eeeff36425863"
metafile = true

[[files]]
file = "mods/smelting-enchantment.pw.toml"
hash = "1c2bdd48c9fcaaac9ed647f9c90d289e1fab5f39ec38e24c0f3eeeff36425863"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "1c2bdd48c9fcaaac9ed647f9c90d289e1fab5f39ec38e24c0f3eeeff36425863"
metafile = true

[[files]]
file = "mods/sound-physics-perfected.pw.toml"
hash = "1c2bdd48c9fcaaac9ed647f9c90d289e1fab5f39ec38e24c0f3eeeff36425863"
metafile = true

[[files]]
file = "mods/spark.pw.toml"
hash = "1c2bdd48c9fcaaac9ed647f9c90d289e1fab5f39ec38e24c0f3eeeff36425863"
metafile = true

[[files]]
file = "mods/status-effect-bars.pw.toml"
hash = "1c2bdd48c9fcaaac9ed647f9c90d289e1fab5f39ec38e24c0f3eeeff36425863"
metafile = true

[[files]]
file = "mods/strawberrylib.pw.toml"
hash = "1c2bdd48c9fcaaac9ed647f9c90d289e1fab5f39ec38e24c0f3eeeff36425863"
metafile = true

[[files]]
file = "mods/supermartijn642s-config-lib.pw.toml"
hash = "1c2bdd48c9fcaaac9ed647f9c90d289e1fab5f39ec38e24c0f3eeeff36425863"
metafile = true

[[files]]
file = "mods/supermartijn642s-core-lib.pw.toml"
hash = "1c2bdd48c9fcaaac9ed647f9c90d289e1fab5f39ec38e24c0f3eeeff36425863"
metafile = true

[[files]]
file = "mods/syncmatica.pw.toml"
hash = "1c2bdd48c9fcaaac9ed647f9c90d289e1fab5f39ec38e24c0f3eeeff36425863"
metafile = true

[[files]]
file = "mods/tax-free-levels.pw.toml"
hash = "1c2bdd48c9fcaaac9ed647f9c90d289e1fab5f39ec38e24c0f3eeeff36425863"
metafile = true

[[files]]
file = "mods/timber-enchantment.pw.toml"
hash = "1c2bdd48c9fcaaac9ed647f9c90d289e1fab5f39ec38e24c0f3eeeff36425863"
metafile = true

[[files]]
file = "mods/toggle-enchants-1.0.0.jar"
hash = "b12d1202d670c195847777ce3a63e78721a6c9fac0e4cb6c45919886e8f600c0"

[[files]]
file = "mods/toms-storage.pw.toml"
hash = "1c2bdd48c9fcaaac9ed647f9c90d289e1fab5f39ec38e24c0f3eeeff36425863"
metafile = true

[[files]]
file = "mods/torcherino(unofficial).pw.toml"
hash = "1c2bdd48c9fcaaac9ed647f9c90d289e1fab5f39ec38e24c0f3eeeff36425863"
metafile = true

[[files]]
file = "mods/tweakermore.pw.toml"
hash = "1c2bdd48c9fcaaac9ed647f9c90d289e1fab5f39ec38e24c0f3eeeff36425863"
metafile = true

[[files]]
file = "mods/tweakeroo.pw.toml"
hash = "1c2bdd48c9fcaaac9ed647f9c90d289e1fab5f39ec38e24c0f3eeeff36425863"
metafile = true

[[files]]
file = "mods/universal-bone-meal.pw.toml"
hash = "1c2bdd48c9fcaaac9ed647f9c90d289e1fab5f39ec38e24c0f3eeeff36425863"
metafile = true

[[files]]
file = "mods/universal-enchants.pw.toml"
hash = "1c2bdd48c9fcaaac9ed647f9c90d289e1fab5f39ec38e24c0f3eeeff36425863"
metafile = true

[[files]]
file = "mods/visual-workbench.pw.toml"
hash = "1c2bdd48c9fcaaac9ed647f9c90d289e1fab5f39ec38e24c0f3eeeff36425863"
metafile = true

[[files]]
file = "mods/waystones.pw.toml"
hash = "1c2bdd48c9fcaaac9ed647f9c90d289e1fab5f39ec38e24c0f3eeeff36425863"
metafile = true

[[files]]
file = "mods/xaeros-minimap.pw.toml"
hash = "1c2bdd48c9fcaaac9ed647f9c90d289e1fab5f39ec38e24c0f3eeeff36425863"
metafile = true

[[files]]
file = "mods/xaeros-world-map.pw.toml"
hash = "1c2bdd48c9fcaaac9ed647f9c90d289e1fab5f39ec38e24c0f3eeeff36425863"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "1c2bdd48c9fcaaac9ed647f9c90d289e1fab5f39ec38e24c0f3eeeff36425863"
metafile = true

[[files]]
file = "pack.png"
hash = "1c2bdd48c9fcaaac9ed647f9c90d289e1fab5f39ec38e24c0f3eeeff36425863"
