name = "Zsl SMP"
author = "wozeparrot"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2246c120c106194852a5a57c959cd0671df7e1b688d72141d022de9453cd805a"

[versions]
fabric = "0.19.3"
minecraft = "26.2"
