name = "Zsl SMP"
author = "wozeparrot"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2e4ee95a8a11442360f08449396d937120eb2b93af9e1e519026794f3750801f"

[versions]
fabric = "0.19.3"
minecraft = "26.2"
