name = "Zsl SMP"
author = "wozeparrot"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "103c797d8dfcf9cc575cd4bd9d249b4881f0049c1a75905e5e800286a23dfff9"

[versions]
fabric = "0.19.3"
minecraft = "26.2"
